<!DOCTYPE html>
<html lang="hu">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
        
    <link rel="stylesheet" href="././public/style.css">
    <title>Bringatúra_MKK</title>
</head>

<body>
    <div class="bg-dark">
        
        <a class="navbar-brand" href="/Bringatura_MKK/">Magyarország Körbe Kerekezve</a>
        <?php //if($params['isAuthorized']): //csak akkor jelenik meg a gomb, ha be van jelentkezve ?>
            <!--<form action="/KODB_PHP15_Orszagok/logout" method="POST">
                <button type="submit" class="btn btn-sm btn-danger m-2">Kijelentkezés</button>
            </form>-->
        <?php //endif; ?>
        </div>
    <nav class="navbar navbar-expand-md bg-light navbar-light sticky-top">
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="index.php">Kezdőoldal</a>
                </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="nav-item">
                    <a class="nav-link" href="bemutatkozas.php">Bemutatkozás</a>
                </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="nav-item">
                    <a class="nav-link" href="tao.php">TAO</a>
                </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">Archívum</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="Arch2021/index.php">2021/2022. bajnoki idény</a>
                        <!--<a class="dropdown-item" href="#">Link 2</a>
                        <a class="dropdown-item" href="#">Link 3</a>-->
                    </div>
                </li>   
            </ul>
        </div>  
    </nav>
    <div class="container">
    <?= $params['content'] ?>
    </div>

</body>

</html>